sudo: false
language: erlang

env:
    - LUA="luajit"

branches:
    only:
        - master

addons:
    apt:
        packages:
            - luajit
            - luarocks

install:
    - luarocks install --local busted
    - luarocks install --local luacov-coveralls

script: "env BUSTED=/home/travis/.luarocks/bin/busted make coverage"

after_success:
    - /home/travis/.luarocks/bin/luacov-coveralls

notifications:
    webhooks:
        - https://webhooks.gitter.im/e/e7f5a3b2ab6ec7c47ed7
    recipients:
        - alex.ellwein@gmail.com
    email:
        on_success: change
        on_failure: always
