sudo: false
language: erlang

env:
  - LUA="luajit"

branches:
  only:
    - master

addons:
    apt:
        packages:
            - luajit
            - luarocks
install:
    - luarocks install --local busted

script: "/home/travis/.luarocks/bin/busted"

notifications:
  webhooks:
    - https://webhooks.gitter.im/e/02362d51814b387a7783
  recipients:
    - alex.ellwein@gmail.com
  email:
    on_success: change
    on_failure: always
