language: erlang

env:
  - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script: "busted spec"

notifications:
  webhooks:
    - https://webhooks.gitter.im/e/02362d51814b387a7783
  recipients:
    - alex.ellwein@gmail.com
  email:
    on_success: change
    on_failure: always
